image: archimg/base-devel:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pacman -Sy --noconfirm --needed emscripten llvm clang cmake ragel make autoconf pkgconfig patch libtool itstool automake python2 zip python2-lxml python2-pip python2-html5lib python2-setuptools python2-chardet python2-virtualenv gperf
  - source /etc/profile.d/emscripten.sh
  - emcc
build: 
  script:
    - make
  artifacts:
    paths:
     - dist/*.*