sudo: required
dist: trusty
env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1 ARCH_TRAVIS_CONFIRM_YES=1
language: nodejs
arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages: # pacman -S emscripten llvm clang cmake nodejs npm ragel wget zip make autoconf pkgconfig patch libtool itstool automake python2 zip python2-lxml python2-pip python2-html5lib python2-setuptools python2-chardet python2-virtualenv jdk8-openjdk gperf
    - emscripten
    - llvm
    - clang
    - cmake
    - nodejs
    - npm
    - ragel
    - wget
    - zip
    - make
    - autoconf
    - pkgconfig
    - patch
    - libtool
    - itstool
    - automake
    - python2
    - zip
    - python2-lxml
    - python2-pip
    - python2-html5lib
    - python2-setuptools
    - python2-chardet
    - python2-virtualenv
    - jdk8-openjdk
    - gperf
  script:
    - sudo sh "./build/ci-build.sh"

script:
 - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
# - zip -r SubtitleOctopus-v$(TRAVIS_TAG).zip js
#after_failure: 
#   - cat ./build/fribidi/config.log
#deploy:
#  provider: releases
#  api_key:
#    secure: 2AKoH11ekUbeMw5jeh2JO2qOfxc4GgSKEOvVAwYIOpEC5gpi7srPKTZkHAXQqErljQ69N6eIRX96/1UYHgiMcAaEPsoT8L9GiL6zbkpJRJ9V3mFAtJbyzmwMDGcr+GoZWQPHrgdWvnAC6R3GmVwVNf5RvvqdMKd2Qh3YV7xmZs7iQioLI1QUWbOiSdde3psa2Cn+rMJ6cKD7QFA7cafoDKEd6vxJA2FTqRNc3ulwDNI1bVosOEu/LQYqkLW2L2kje5QBXu7wWZpWp9PeHyvAp2xmy4TBOZ+YMAut6uP9rnUVciZe1pJEOzjUa2cH+1e+NNwlm7GW9uNTBT4pTLdqPLzbNYnB2+a5rxVzFt4RGaMuT39eMb67M8/wew/DKN1ypQFGbMZ3Z5VRY/2SLhH1vCcV8APQyxzovY++qrsOusVelBbj/47QQTXpBkkJ5KpN1BsJ2WYBKwdrxrrGEr/s2pWOLmNuBWyhm+FpW/DjcXj6Cmu3YpcGM5Ua3uFMvPw29r5q0Neg3jrSIaVx9a9yu+jzmJ1JvNgyWGVW7SfRNvwJi8hUs2Z0OTXKZSmIQkdthsBgPSFqGCm9ScvD4HO5jL1r3RVLldCDabtWp+In2N6quvhir62jjKQ3myW3C7r9l2YbeVXId/KJmol1eZBXN3oL9HIjsNMqnUNtlDMGFeI=
#  file: 'SubtitleOctopus-v$(TRAVIS_TAG).zip'
#  file_blob: true
#  skip-cleanup: true
#  on:
#    tags: true
